server:
  port: 3004

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${PG_URI}
    password: ${PG_PASSWORD}
    username: ${PB_USERNAME}
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true