server:
  port: 3001

spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: cart

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true